name: "CI/CD"
on: [push]
 
jobs:
  CI:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v1
        with:
          java-version: 17.0
 
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Compile
        run: mvn -B clean package -DskipTests
        working-directory: AtlasParent/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Atlas
        uses: actions/upload-artifact@v2
        with:
          name: AtlasBukkit
          path: AtlasParent/AtlasBukkit/target/AtlasBukkit-*.jar
      - name:  Upload AtlasBungee
        uses: actions/upload-artifact@v2
        with:
          name: AtlasBungee
          path: AtlasParent/AtlasBungee/target/AtlasBungee-*.jar
      - name: Upload AtlasVelocity
        uses: actions/upload-artifact@v2
        with:
          name: AtlasVelocity
          path: AtlasParent/AtlasVelocity/target/AtlasVelocity-*.jar
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.funkemunky.cc
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          format: maven2
          repository: snapshots
          coordinates: groupId=cc.funkemunky.plugins artifactId=Atlas version=latest
          assets: extension=jar
          filename: AtlasParent/AtlasBukkit/target/AtlasBukkit-*.jar


